// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/user/v1/user_service.proto

package userv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserOrderService_SetOrder_FullMethodName      = "/user.v1.UserOrderService/SetOrder"
	UserOrderService_WithdrawOrder_FullMethodName = "/user.v1.UserOrderService/WithdrawOrder"
	UserOrderService_ListOrders_FullMethodName    = "/user.v1.UserOrderService/ListOrders"
)

// UserOrderServiceClient is the client API for UserOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserOrderServiceClient interface {
	SetOrder(ctx context.Context, in *SetOrderRequest, opts ...grpc.CallOption) (*SetOrderResponse, error)
	WithdrawOrder(ctx context.Context, in *WithdrawOrderRequest, opts ...grpc.CallOption) (*WithdrawOrderResponse, error)
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
}

type userOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserOrderServiceClient(cc grpc.ClientConnInterface) UserOrderServiceClient {
	return &userOrderServiceClient{cc}
}

func (c *userOrderServiceClient) SetOrder(ctx context.Context, in *SetOrderRequest, opts ...grpc.CallOption) (*SetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetOrderResponse)
	err := c.cc.Invoke(ctx, UserOrderService_SetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOrderServiceClient) WithdrawOrder(ctx context.Context, in *WithdrawOrderRequest, opts ...grpc.CallOption) (*WithdrawOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawOrderResponse)
	err := c.cc.Invoke(ctx, UserOrderService_WithdrawOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOrderServiceClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersResponse)
	err := c.cc.Invoke(ctx, UserOrderService_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserOrderServiceServer is the server API for UserOrderService service.
// All implementations must embed UnimplementedUserOrderServiceServer
// for forward compatibility.
type UserOrderServiceServer interface {
	SetOrder(context.Context, *SetOrderRequest) (*SetOrderResponse, error)
	WithdrawOrder(context.Context, *WithdrawOrderRequest) (*WithdrawOrderResponse, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	mustEmbedUnimplementedUserOrderServiceServer()
}

// UnimplementedUserOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserOrderServiceServer struct{}

func (UnimplementedUserOrderServiceServer) SetOrder(context.Context, *SetOrderRequest) (*SetOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetOrder not implemented")
}
func (UnimplementedUserOrderServiceServer) WithdrawOrder(context.Context, *WithdrawOrderRequest) (*WithdrawOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawOrder not implemented")
}
func (UnimplementedUserOrderServiceServer) ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedUserOrderServiceServer) mustEmbedUnimplementedUserOrderServiceServer() {}
func (UnimplementedUserOrderServiceServer) testEmbeddedByValue()                          {}

// UnsafeUserOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserOrderServiceServer will
// result in compilation errors.
type UnsafeUserOrderServiceServer interface {
	mustEmbedUnimplementedUserOrderServiceServer()
}

func RegisterUserOrderServiceServer(s grpc.ServiceRegistrar, srv UserOrderServiceServer) {
	// If the following call panics, it indicates UnimplementedUserOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserOrderService_ServiceDesc, srv)
}

func _UserOrderService_SetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOrderServiceServer).SetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOrderService_SetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOrderServiceServer).SetOrder(ctx, req.(*SetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOrderService_WithdrawOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOrderServiceServer).WithdrawOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOrderService_WithdrawOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOrderServiceServer).WithdrawOrder(ctx, req.(*WithdrawOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOrderService_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOrderServiceServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserOrderService_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOrderServiceServer).ListOrders(ctx, req.(*ListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserOrderService_ServiceDesc is the grpc.ServiceDesc for UserOrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserOrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.UserOrderService",
	HandlerType: (*UserOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetOrder",
			Handler:    _UserOrderService_SetOrder_Handler,
		},
		{
			MethodName: "WithdrawOrder",
			Handler:    _UserOrderService_WithdrawOrder_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _UserOrderService_ListOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/v1/user_service.proto",
}
