// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/user/v1/user_service.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status enumerates order states.
type Status int32

const (
	Status_UNSPECIFIED Status = 0
	Status_PLACED      Status = 1
	Status_DELIVERED   Status = 2
	Status_EN_ROUTE    Status = 3
	Status_FAILED      Status = 4
	Status_TO_PICK_UP  Status = 5
	Status_WITHDRAWN   Status = 6
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "PLACED",
		2: "DELIVERED",
		3: "EN_ROUTE",
		4: "FAILED",
		5: "TO_PICK_UP",
		6: "WITHDRAWN",
	}
	Status_value = map[string]int32{
		"UNSPECIFIED": 0,
		"PLACED":      1,
		"DELIVERED":   2,
		"EN_ROUTE":    3,
		"FAILED":      4,
		"TO_PICK_UP":  5,
		"WITHDRAWN":   6,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_user_v1_user_service_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_user_v1_user_service_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_user_v1_user_service_proto_rawDescGZIP(), []int{0}
}

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_api_user_v1_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinates) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Coordinates) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin        *Coordinates           `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   *Coordinates           `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=user.v1.Status" json:"status,omitempty"`
	SubmittedBy   int64                  `protobuf:"varint,5,opt,name=submitted_by,json=submittedBy,proto3" json:"submitted_by,omitempty"`
	PlacementDate string                 `protobuf:"bytes,6,opt,name=placement_date,json=placementDate,proto3" json:"placement_date,omitempty"` // RFC3339 or database string representation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_user_v1_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetOrigin() *Coordinates {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *Order) GetDestination() *Coordinates {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Order) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNSPECIFIED
}

func (x *Order) GetSubmittedBy() int64 {
	if x != nil {
		return x.SubmittedBy
	}
	return 0
}

func (x *Order) GetPlacementDate() string {
	if x != nil {
		return x.PlacementDate
	}
	return ""
}

type SetOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The caller identity is taken from JWT; this request only carries coordinates.
	Origin        *Coordinates `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   *Coordinates `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOrderRequest) Reset() {
	*x = SetOrderRequest{}
	mi := &file_api_user_v1_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrderRequest) ProtoMessage() {}

func (x *SetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrderRequest.ProtoReflect.Descriptor instead.
func (*SetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *SetOrderRequest) GetOrigin() *Coordinates {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *SetOrderRequest) GetDestination() *Coordinates {
	if x != nil {
		return x.Destination
	}
	return nil
}

type SetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOrderResponse) Reset() {
	*x = SetOrderResponse{}
	mi := &file_api_user_v1_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrderResponse) ProtoMessage() {}

func (x *SetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrderResponse.ProtoReflect.Descriptor instead.
func (*SetOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *SetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type WithdrawOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawOrderRequest) Reset() {
	*x = WithdrawOrderRequest{}
	mi := &file_api_user_v1_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawOrderRequest) ProtoMessage() {}

func (x *WithdrawOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawOrderRequest.ProtoReflect.Descriptor instead.
func (*WithdrawOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *WithdrawOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type WithdrawOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"` // updated order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawOrderResponse) Reset() {
	*x = WithdrawOrderResponse{}
	mi := &file_api_user_v1_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawOrderResponse) ProtoMessage() {}

func (x *WithdrawOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawOrderResponse.ProtoReflect.Descriptor instead.
func (*WithdrawOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *WithdrawOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard pagination fields following Google API style.
	// If unset, the server applies a sensible default page size.
	PageSize      int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // max items to return (server-enforced cap)
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // opaque token from a previous ListOrdersResponse
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_api_user_v1_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // empty if there are no more results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_api_user_v1_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_api_user_v1_user_service_proto protoreflect.FileDescriptor

const file_api_user_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/user/v1/user_service.proto\x12\auser.v1\"1\n" +
	"\vCoordinates\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"\xf0\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12,\n" +
	"\x06origin\x18\x02 \x01(\v2\x14.user.v1.CoordinatesR\x06origin\x126\n" +
	"\vdestination\x18\x03 \x01(\v2\x14.user.v1.CoordinatesR\vdestination\x12'\n" +
	"\x06status\x18\x04 \x01(\x0e2\x0f.user.v1.StatusR\x06status\x12!\n" +
	"\fsubmitted_by\x18\x05 \x01(\x03R\vsubmittedBy\x12%\n" +
	"\x0eplacement_date\x18\x06 \x01(\tR\rplacementDate\"w\n" +
	"\x0fSetOrderRequest\x12,\n" +
	"\x06origin\x18\x01 \x01(\v2\x14.user.v1.CoordinatesR\x06origin\x126\n" +
	"\vdestination\x18\x02 \x01(\v2\x14.user.v1.CoordinatesR\vdestination\"8\n" +
	"\x10SetOrderResponse\x12$\n" +
	"\x05order\x18\x01 \x01(\v2\x0e.user.v1.OrderR\x05order\"1\n" +
	"\x14WithdrawOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"=\n" +
	"\x15WithdrawOrderResponse\x12$\n" +
	"\x05order\x18\x01 \x01(\v2\x0e.user.v1.OrderR\x05order\"O\n" +
	"\x11ListOrdersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"d\n" +
	"\x12ListOrdersResponse\x12&\n" +
	"\x06orders\x18\x01 \x03(\v2\x0e.user.v1.OrderR\x06orders\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*m\n" +
	"\x06Status\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PLACED\x10\x01\x12\r\n" +
	"\tDELIVERED\x10\x02\x12\f\n" +
	"\bEN_ROUTE\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\x0e\n" +
	"\n" +
	"TO_PICK_UP\x10\x05\x12\r\n" +
	"\tWITHDRAWN\x10\x062\xea\x01\n" +
	"\x10UserOrderService\x12?\n" +
	"\bSetOrder\x12\x18.user.v1.SetOrderRequest\x1a\x19.user.v1.SetOrderResponse\x12N\n" +
	"\rWithdrawOrder\x12\x1d.user.v1.WithdrawOrderRequest\x1a\x1e.user.v1.WithdrawOrderResponse\x12E\n" +
	"\n" +
	"ListOrders\x12\x1a.user.v1.ListOrdersRequest\x1a\x1b.user.v1.ListOrdersResponseB,Z*droneDeliveryManagement/api/user/v1;userv1b\x06proto3"

var (
	file_api_user_v1_user_service_proto_rawDescOnce sync.Once
	file_api_user_v1_user_service_proto_rawDescData []byte
)

func file_api_user_v1_user_service_proto_rawDescGZIP() []byte {
	file_api_user_v1_user_service_proto_rawDescOnce.Do(func() {
		file_api_user_v1_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_user_service_proto_rawDesc), len(file_api_user_v1_user_service_proto_rawDesc)))
	})
	return file_api_user_v1_user_service_proto_rawDescData
}

var file_api_user_v1_user_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_user_v1_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_user_v1_user_service_proto_goTypes = []any{
	(Status)(0),                   // 0: user.v1.Status
	(*Coordinates)(nil),           // 1: user.v1.Coordinates
	(*Order)(nil),                 // 2: user.v1.Order
	(*SetOrderRequest)(nil),       // 3: user.v1.SetOrderRequest
	(*SetOrderResponse)(nil),      // 4: user.v1.SetOrderResponse
	(*WithdrawOrderRequest)(nil),  // 5: user.v1.WithdrawOrderRequest
	(*WithdrawOrderResponse)(nil), // 6: user.v1.WithdrawOrderResponse
	(*ListOrdersRequest)(nil),     // 7: user.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),    // 8: user.v1.ListOrdersResponse
}
var file_api_user_v1_user_service_proto_depIdxs = []int32{
	1,  // 0: user.v1.Order.origin:type_name -> user.v1.Coordinates
	1,  // 1: user.v1.Order.destination:type_name -> user.v1.Coordinates
	0,  // 2: user.v1.Order.status:type_name -> user.v1.Status
	1,  // 3: user.v1.SetOrderRequest.origin:type_name -> user.v1.Coordinates
	1,  // 4: user.v1.SetOrderRequest.destination:type_name -> user.v1.Coordinates
	2,  // 5: user.v1.SetOrderResponse.order:type_name -> user.v1.Order
	2,  // 6: user.v1.WithdrawOrderResponse.order:type_name -> user.v1.Order
	2,  // 7: user.v1.ListOrdersResponse.orders:type_name -> user.v1.Order
	3,  // 8: user.v1.UserOrderService.SetOrder:input_type -> user.v1.SetOrderRequest
	5,  // 9: user.v1.UserOrderService.WithdrawOrder:input_type -> user.v1.WithdrawOrderRequest
	7,  // 10: user.v1.UserOrderService.ListOrders:input_type -> user.v1.ListOrdersRequest
	4,  // 11: user.v1.UserOrderService.SetOrder:output_type -> user.v1.SetOrderResponse
	6,  // 12: user.v1.UserOrderService.WithdrawOrder:output_type -> user.v1.WithdrawOrderResponse
	8,  // 13: user.v1.UserOrderService.ListOrders:output_type -> user.v1.ListOrdersResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_user_v1_user_service_proto_init() }
func file_api_user_v1_user_service_proto_init() {
	if File_api_user_v1_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_user_service_proto_rawDesc), len(file_api_user_v1_user_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v1_user_service_proto_goTypes,
		DependencyIndexes: file_api_user_v1_user_service_proto_depIdxs,
		EnumInfos:         file_api_user_v1_user_service_proto_enumTypes,
		MessageInfos:      file_api_user_v1_user_service_proto_msgTypes,
	}.Build()
	File_api_user_v1_user_service_proto = out.File
	file_api_user_v1_user_service_proto_goTypes = nil
	file_api_user_v1_user_service_proto_depIdxs = nil
}
