// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/drone/v1/drone_service.proto

package dronev1

import (
	v1 "droneDeliveryManagement/api/user/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reserve an available order for this drone.
type ReserveOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveOrderRequest) Reset() {
	*x = ReserveOrderRequest{}
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveOrderRequest) ProtoMessage() {}

func (x *ReserveOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveOrderRequest.ProtoReflect.Descriptor instead.
func (*ReserveOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_drone_v1_drone_service_proto_rawDescGZIP(), []int{0}
}

type ReserveOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *v1.Order              `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveOrderResponse) Reset() {
	*x = ReserveOrderResponse{}
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveOrderResponse) ProtoMessage() {}

func (x *ReserveOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveOrderResponse.ProtoReflect.Descriptor instead.
func (*ReserveOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_drone_v1_drone_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveOrderResponse) GetOrder() *v1.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// Attempt to grab the currently assigned order (transition to EN_ROUTE when near pickup/origin).
type GrabOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrabOrderRequest) Reset() {
	*x = GrabOrderRequest{}
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrabOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrabOrderRequest) ProtoMessage() {}

func (x *GrabOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrabOrderRequest.ProtoReflect.Descriptor instead.
func (*GrabOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_drone_v1_drone_service_proto_rawDescGZIP(), []int{2}
}

type GrabOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *v1.Order              `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrabOrderResponse) Reset() {
	*x = GrabOrderResponse{}
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrabOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrabOrderResponse) ProtoMessage() {}

func (x *GrabOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrabOrderResponse.ProtoReflect.Descriptor instead.
func (*GrabOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_drone_v1_drone_service_proto_rawDescGZIP(), []int{3}
}

func (x *GrabOrderResponse) GetOrder() *v1.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// Complete the currently assigned order as delivered or failed (when near destination).
type CompleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"` // true: delivered, false: failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOrderRequest) Reset() {
	*x = CompleteOrderRequest{}
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderRequest) ProtoMessage() {}

func (x *CompleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderRequest.ProtoReflect.Descriptor instead.
func (*CompleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_drone_v1_drone_service_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteOrderRequest) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

type CompleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *v1.Order              `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOrderResponse) Reset() {
	*x = CompleteOrderResponse{}
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderResponse) ProtoMessage() {}

func (x *CompleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderResponse.ProtoReflect.Descriptor instead.
func (*CompleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_drone_v1_drone_service_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteOrderResponse) GetOrder() *v1.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// Mark this drone as broken and perform handoff logic if it has an assigned job.
type MarkBrokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkBrokenRequest) Reset() {
	*x = MarkBrokenRequest{}
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkBrokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkBrokenRequest) ProtoMessage() {}

func (x *MarkBrokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkBrokenRequest.ProtoReflect.Descriptor instead.
func (*MarkBrokenRequest) Descriptor() ([]byte, []int) {
	return file_api_drone_v1_drone_service_proto_rawDescGZIP(), []int{6}
}

type MarkBrokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *v1.Order              `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"` // if there was an order affected (may be empty)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkBrokenResponse) Reset() {
	*x = MarkBrokenResponse{}
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkBrokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkBrokenResponse) ProtoMessage() {}

func (x *MarkBrokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkBrokenResponse.ProtoReflect.Descriptor instead.
func (*MarkBrokenResponse) Descriptor() ([]byte, []int) {
	return file_api_drone_v1_drone_service_proto_rawDescGZIP(), []int{7}
}

func (x *MarkBrokenResponse) GetOrder() *v1.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// Heartbeat updates the drone's current location and speed.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *v1.Coordinates        `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	SpeedMph      float64                `protobuf:"fixed64,2,opt,name=speed_mph,json=speedMph,proto3" json:"speed_mph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_drone_v1_drone_service_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetLocation() *v1.Coordinates {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *HeartbeatRequest) GetSpeedMph() float64 {
	if x != nil {
		return x.SpeedMph
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_drone_v1_drone_service_proto_rawDescGZIP(), []int{9}
}

// Get the currently assigned order and computed ETA in seconds.
type GetAssignedOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignedOrderRequest) Reset() {
	*x = GetAssignedOrderRequest{}
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignedOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignedOrderRequest) ProtoMessage() {}

func (x *GetAssignedOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignedOrderRequest.ProtoReflect.Descriptor instead.
func (*GetAssignedOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_drone_v1_drone_service_proto_rawDescGZIP(), []int{10}
}

type GetAssignedOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *v1.Order              `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	EtaSeconds    float64                `protobuf:"fixed64,2,opt,name=eta_seconds,json=etaSeconds,proto3" json:"eta_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignedOrderResponse) Reset() {
	*x = GetAssignedOrderResponse{}
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignedOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignedOrderResponse) ProtoMessage() {}

func (x *GetAssignedOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_drone_v1_drone_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignedOrderResponse.ProtoReflect.Descriptor instead.
func (*GetAssignedOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_drone_v1_drone_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetAssignedOrderResponse) GetOrder() *v1.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *GetAssignedOrderResponse) GetEtaSeconds() float64 {
	if x != nil {
		return x.EtaSeconds
	}
	return 0
}

var File_api_drone_v1_drone_service_proto protoreflect.FileDescriptor

const file_api_drone_v1_drone_service_proto_rawDesc = "" +
	"\n" +
	" api/drone/v1/drone_service.proto\x12\bdrone.v1\x1a\x1eapi/user/v1/user_service.proto\"\x15\n" +
	"\x13ReserveOrderRequest\"<\n" +
	"\x14ReserveOrderResponse\x12$\n" +
	"\x05order\x18\x01 \x01(\v2\x0e.user.v1.OrderR\x05order\"\x12\n" +
	"\x10GrabOrderRequest\"9\n" +
	"\x11GrabOrderResponse\x12$\n" +
	"\x05order\x18\x01 \x01(\v2\x0e.user.v1.OrderR\x05order\"4\n" +
	"\x14CompleteOrderRequest\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\"=\n" +
	"\x15CompleteOrderResponse\x12$\n" +
	"\x05order\x18\x01 \x01(\v2\x0e.user.v1.OrderR\x05order\"\x13\n" +
	"\x11MarkBrokenRequest\":\n" +
	"\x12MarkBrokenResponse\x12$\n" +
	"\x05order\x18\x01 \x01(\v2\x0e.user.v1.OrderR\x05order\"a\n" +
	"\x10HeartbeatRequest\x120\n" +
	"\blocation\x18\x01 \x01(\v2\x14.user.v1.CoordinatesR\blocation\x12\x1b\n" +
	"\tspeed_mph\x18\x02 \x01(\x01R\bspeedMph\"\x13\n" +
	"\x11HeartbeatResponse\"\x19\n" +
	"\x17GetAssignedOrderRequest\"a\n" +
	"\x18GetAssignedOrderResponse\x12$\n" +
	"\x05order\x18\x01 \x01(\v2\x0e.user.v1.OrderR\x05order\x12\x1f\n" +
	"\veta_seconds\x18\x02 \x01(\x01R\n" +
	"etaSeconds2\xdf\x03\n" +
	"\fDroneService\x12M\n" +
	"\fReserveOrder\x12\x1d.drone.v1.ReserveOrderRequest\x1a\x1e.drone.v1.ReserveOrderResponse\x12D\n" +
	"\tGrabOrder\x12\x1a.drone.v1.GrabOrderRequest\x1a\x1b.drone.v1.GrabOrderResponse\x12P\n" +
	"\rCompleteOrder\x12\x1e.drone.v1.CompleteOrderRequest\x1a\x1f.drone.v1.CompleteOrderResponse\x12G\n" +
	"\n" +
	"MarkBroken\x12\x1b.drone.v1.MarkBrokenRequest\x1a\x1c.drone.v1.MarkBrokenResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.drone.v1.HeartbeatRequest\x1a\x1b.drone.v1.HeartbeatResponse\x12Y\n" +
	"\x10GetAssignedOrder\x12!.drone.v1.GetAssignedOrderRequest\x1a\".drone.v1.GetAssignedOrderResponseB.Z,droneDeliveryManagement/api/drone/v1;dronev1b\x06proto3"

var (
	file_api_drone_v1_drone_service_proto_rawDescOnce sync.Once
	file_api_drone_v1_drone_service_proto_rawDescData []byte
)

func file_api_drone_v1_drone_service_proto_rawDescGZIP() []byte {
	file_api_drone_v1_drone_service_proto_rawDescOnce.Do(func() {
		file_api_drone_v1_drone_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_drone_v1_drone_service_proto_rawDesc), len(file_api_drone_v1_drone_service_proto_rawDesc)))
	})
	return file_api_drone_v1_drone_service_proto_rawDescData
}

var file_api_drone_v1_drone_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_drone_v1_drone_service_proto_goTypes = []any{
	(*ReserveOrderRequest)(nil),      // 0: drone.v1.ReserveOrderRequest
	(*ReserveOrderResponse)(nil),     // 1: drone.v1.ReserveOrderResponse
	(*GrabOrderRequest)(nil),         // 2: drone.v1.GrabOrderRequest
	(*GrabOrderResponse)(nil),        // 3: drone.v1.GrabOrderResponse
	(*CompleteOrderRequest)(nil),     // 4: drone.v1.CompleteOrderRequest
	(*CompleteOrderResponse)(nil),    // 5: drone.v1.CompleteOrderResponse
	(*MarkBrokenRequest)(nil),        // 6: drone.v1.MarkBrokenRequest
	(*MarkBrokenResponse)(nil),       // 7: drone.v1.MarkBrokenResponse
	(*HeartbeatRequest)(nil),         // 8: drone.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 9: drone.v1.HeartbeatResponse
	(*GetAssignedOrderRequest)(nil),  // 10: drone.v1.GetAssignedOrderRequest
	(*GetAssignedOrderResponse)(nil), // 11: drone.v1.GetAssignedOrderResponse
	(*v1.Order)(nil),                 // 12: user.v1.Order
	(*v1.Coordinates)(nil),           // 13: user.v1.Coordinates
}
var file_api_drone_v1_drone_service_proto_depIdxs = []int32{
	12, // 0: drone.v1.ReserveOrderResponse.order:type_name -> user.v1.Order
	12, // 1: drone.v1.GrabOrderResponse.order:type_name -> user.v1.Order
	12, // 2: drone.v1.CompleteOrderResponse.order:type_name -> user.v1.Order
	12, // 3: drone.v1.MarkBrokenResponse.order:type_name -> user.v1.Order
	13, // 4: drone.v1.HeartbeatRequest.location:type_name -> user.v1.Coordinates
	12, // 5: drone.v1.GetAssignedOrderResponse.order:type_name -> user.v1.Order
	0,  // 6: drone.v1.DroneService.ReserveOrder:input_type -> drone.v1.ReserveOrderRequest
	2,  // 7: drone.v1.DroneService.GrabOrder:input_type -> drone.v1.GrabOrderRequest
	4,  // 8: drone.v1.DroneService.CompleteOrder:input_type -> drone.v1.CompleteOrderRequest
	6,  // 9: drone.v1.DroneService.MarkBroken:input_type -> drone.v1.MarkBrokenRequest
	8,  // 10: drone.v1.DroneService.Heartbeat:input_type -> drone.v1.HeartbeatRequest
	10, // 11: drone.v1.DroneService.GetAssignedOrder:input_type -> drone.v1.GetAssignedOrderRequest
	1,  // 12: drone.v1.DroneService.ReserveOrder:output_type -> drone.v1.ReserveOrderResponse
	3,  // 13: drone.v1.DroneService.GrabOrder:output_type -> drone.v1.GrabOrderResponse
	5,  // 14: drone.v1.DroneService.CompleteOrder:output_type -> drone.v1.CompleteOrderResponse
	7,  // 15: drone.v1.DroneService.MarkBroken:output_type -> drone.v1.MarkBrokenResponse
	9,  // 16: drone.v1.DroneService.Heartbeat:output_type -> drone.v1.HeartbeatResponse
	11, // 17: drone.v1.DroneService.GetAssignedOrder:output_type -> drone.v1.GetAssignedOrderResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_drone_v1_drone_service_proto_init() }
func file_api_drone_v1_drone_service_proto_init() {
	if File_api_drone_v1_drone_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_drone_v1_drone_service_proto_rawDesc), len(file_api_drone_v1_drone_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_drone_v1_drone_service_proto_goTypes,
		DependencyIndexes: file_api_drone_v1_drone_service_proto_depIdxs,
		MessageInfos:      file_api_drone_v1_drone_service_proto_msgTypes,
	}.Build()
	File_api_drone_v1_drone_service_proto = out.File
	file_api_drone_v1_drone_service_proto_goTypes = nil
	file_api_drone_v1_drone_service_proto_depIdxs = nil
}
