// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/drone/v1/drone_service.proto

package dronev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DroneService_ReserveOrder_FullMethodName     = "/drone.v1.DroneService/ReserveOrder"
	DroneService_GrabOrder_FullMethodName        = "/drone.v1.DroneService/GrabOrder"
	DroneService_CompleteOrder_FullMethodName    = "/drone.v1.DroneService/CompleteOrder"
	DroneService_MarkBroken_FullMethodName       = "/drone.v1.DroneService/MarkBroken"
	DroneService_Heartbeat_FullMethodName        = "/drone.v1.DroneService/Heartbeat"
	DroneService_GetAssignedOrder_FullMethodName = "/drone.v1.DroneService/GetAssignedOrder"
)

// DroneServiceClient is the client API for DroneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DroneServiceClient interface {
	ReserveOrder(ctx context.Context, in *ReserveOrderRequest, opts ...grpc.CallOption) (*ReserveOrderResponse, error)
	GrabOrder(ctx context.Context, in *GrabOrderRequest, opts ...grpc.CallOption) (*GrabOrderResponse, error)
	CompleteOrder(ctx context.Context, in *CompleteOrderRequest, opts ...grpc.CallOption) (*CompleteOrderResponse, error)
	MarkBroken(ctx context.Context, in *MarkBrokenRequest, opts ...grpc.CallOption) (*MarkBrokenResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	GetAssignedOrder(ctx context.Context, in *GetAssignedOrderRequest, opts ...grpc.CallOption) (*GetAssignedOrderResponse, error)
}

type droneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDroneServiceClient(cc grpc.ClientConnInterface) DroneServiceClient {
	return &droneServiceClient{cc}
}

func (c *droneServiceClient) ReserveOrder(ctx context.Context, in *ReserveOrderRequest, opts ...grpc.CallOption) (*ReserveOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveOrderResponse)
	err := c.cc.Invoke(ctx, DroneService_ReserveOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneServiceClient) GrabOrder(ctx context.Context, in *GrabOrderRequest, opts ...grpc.CallOption) (*GrabOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrabOrderResponse)
	err := c.cc.Invoke(ctx, DroneService_GrabOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneServiceClient) CompleteOrder(ctx context.Context, in *CompleteOrderRequest, opts ...grpc.CallOption) (*CompleteOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteOrderResponse)
	err := c.cc.Invoke(ctx, DroneService_CompleteOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneServiceClient) MarkBroken(ctx context.Context, in *MarkBrokenRequest, opts ...grpc.CallOption) (*MarkBrokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkBrokenResponse)
	err := c.cc.Invoke(ctx, DroneService_MarkBroken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, DroneService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneServiceClient) GetAssignedOrder(ctx context.Context, in *GetAssignedOrderRequest, opts ...grpc.CallOption) (*GetAssignedOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssignedOrderResponse)
	err := c.cc.Invoke(ctx, DroneService_GetAssignedOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DroneServiceServer is the server API for DroneService service.
// All implementations must embed UnimplementedDroneServiceServer
// for forward compatibility.
type DroneServiceServer interface {
	ReserveOrder(context.Context, *ReserveOrderRequest) (*ReserveOrderResponse, error)
	GrabOrder(context.Context, *GrabOrderRequest) (*GrabOrderResponse, error)
	CompleteOrder(context.Context, *CompleteOrderRequest) (*CompleteOrderResponse, error)
	MarkBroken(context.Context, *MarkBrokenRequest) (*MarkBrokenResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	GetAssignedOrder(context.Context, *GetAssignedOrderRequest) (*GetAssignedOrderResponse, error)
	mustEmbedUnimplementedDroneServiceServer()
}

// UnimplementedDroneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDroneServiceServer struct{}

func (UnimplementedDroneServiceServer) ReserveOrder(context.Context, *ReserveOrderRequest) (*ReserveOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveOrder not implemented")
}
func (UnimplementedDroneServiceServer) GrabOrder(context.Context, *GrabOrderRequest) (*GrabOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrabOrder not implemented")
}
func (UnimplementedDroneServiceServer) CompleteOrder(context.Context, *CompleteOrderRequest) (*CompleteOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteOrder not implemented")
}
func (UnimplementedDroneServiceServer) MarkBroken(context.Context, *MarkBrokenRequest) (*MarkBrokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkBroken not implemented")
}
func (UnimplementedDroneServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedDroneServiceServer) GetAssignedOrder(context.Context, *GetAssignedOrderRequest) (*GetAssignedOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssignedOrder not implemented")
}
func (UnimplementedDroneServiceServer) mustEmbedUnimplementedDroneServiceServer() {}
func (UnimplementedDroneServiceServer) testEmbeddedByValue()                      {}

// UnsafeDroneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DroneServiceServer will
// result in compilation errors.
type UnsafeDroneServiceServer interface {
	mustEmbedUnimplementedDroneServiceServer()
}

func RegisterDroneServiceServer(s grpc.ServiceRegistrar, srv DroneServiceServer) {
	// If the following call panics, it indicates UnimplementedDroneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DroneService_ServiceDesc, srv)
}

func _DroneService_ReserveOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).ReserveOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_ReserveOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).ReserveOrder(ctx, req.(*ReserveOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneService_GrabOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrabOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).GrabOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_GrabOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).GrabOrder(ctx, req.(*GrabOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneService_CompleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).CompleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_CompleteOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).CompleteOrder(ctx, req.(*CompleteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneService_MarkBroken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkBrokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).MarkBroken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_MarkBroken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).MarkBroken(ctx, req.(*MarkBrokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneService_GetAssignedOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssignedOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).GetAssignedOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_GetAssignedOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).GetAssignedOrder(ctx, req.(*GetAssignedOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DroneService_ServiceDesc is the grpc.ServiceDesc for DroneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DroneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone.v1.DroneService",
	HandlerType: (*DroneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveOrder",
			Handler:    _DroneService_ReserveOrder_Handler,
		},
		{
			MethodName: "GrabOrder",
			Handler:    _DroneService_GrabOrder_Handler,
		},
		{
			MethodName: "CompleteOrder",
			Handler:    _DroneService_CompleteOrder_Handler,
		},
		{
			MethodName: "MarkBroken",
			Handler:    _DroneService_MarkBroken_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _DroneService_Heartbeat_Handler,
		},
		{
			MethodName: "GetAssignedOrder",
			Handler:    _DroneService_GetAssignedOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/drone/v1/drone_service.proto",
}
