// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/admin/v1/admin_service.proto

package adminv1

import (
	v1 "droneDeliveryManagement/api/user/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Drone status for admin operations.
type DroneStatus int32

const (
	DroneStatus_DRONE_STATUS_UNSPECIFIED DroneStatus = 0
	DroneStatus_DRONE_STATUS_FIXED       DroneStatus = 1
	DroneStatus_DRONE_STATUS_BROKEN      DroneStatus = 2
)

// Enum value maps for DroneStatus.
var (
	DroneStatus_name = map[int32]string{
		0: "DRONE_STATUS_UNSPECIFIED",
		1: "DRONE_STATUS_FIXED",
		2: "DRONE_STATUS_BROKEN",
	}
	DroneStatus_value = map[string]int32{
		"DRONE_STATUS_UNSPECIFIED": 0,
		"DRONE_STATUS_FIXED":       1,
		"DRONE_STATUS_BROKEN":      2,
	}
)

func (x DroneStatus) Enum() *DroneStatus {
	p := new(DroneStatus)
	*p = x
	return p
}

func (x DroneStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DroneStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_admin_v1_admin_service_proto_enumTypes[0].Descriptor()
}

func (DroneStatus) Type() protoreflect.EnumType {
	return &file_api_admin_v1_admin_service_proto_enumTypes[0]
}

func (x DroneStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DroneStatus.Descriptor instead.
func (DroneStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_service_proto_rawDescGZIP(), []int{0}
}

type Drone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Lat           float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,5,opt,name=lng,proto3" json:"lng,omitempty"`
	SpeedMph      float64                `protobuf:"fixed64,6,opt,name=speed_mph,json=speedMph,proto3" json:"speed_mph,omitempty"`
	AssignedJob   *int64                 `protobuf:"varint,7,opt,name=assigned_job,json=assignedJob,proto3,oneof" json:"assigned_job,omitempty"` // may be unset
	Status        DroneStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=admin.v1.DroneStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drone) Reset() {
	*x = Drone{}
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drone) ProtoMessage() {}

func (x *Drone) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drone.ProtoReflect.Descriptor instead.
func (*Drone) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_service_proto_rawDescGZIP(), []int{0}
}

func (x *Drone) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Drone) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Drone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Drone) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Drone) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Drone) GetSpeedMph() float64 {
	if x != nil {
		return x.SpeedMph
	}
	return 0
}

func (x *Drone) GetAssignedJob() int64 {
	if x != nil && x.AssignedJob != nil {
		return *x.AssignedJob
	}
	return 0
}

func (x *Drone) GetStatus() DroneStatus {
	if x != nil {
		return x.Status
	}
	return DroneStatus_DRONE_STATUS_UNSPECIFIED
}

type GetOrdersRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter []v1.Status            `protobuf:"varint,1,rep,packed,name=status_filter,json=statusFilter,proto3,enum=user.v1.Status" json:"status_filter,omitempty"`
	SubmittedBy  *int64                 `protobuf:"varint,2,opt,name=submitted_by,json=submittedBy,proto3,oneof" json:"submitted_by,omitempty"`
	// placement_date range (inclusive). RFC3339 or SQLite "YYYY-MM-DD HH:MM:SS" formats accepted.
	PlacementFrom *string `protobuf:"bytes,3,opt,name=placement_from,json=placementFrom,proto3,oneof" json:"placement_from,omitempty"`
	PlacementTo   *string `protobuf:"bytes,4,opt,name=placement_to,json=placementTo,proto3,oneof" json:"placement_to,omitempty"`
	PageSize      int32   `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string  `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // opaque; generated by server
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersRequest) Reset() {
	*x = GetOrdersRequest{}
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersRequest) ProtoMessage() {}

func (x *GetOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrdersRequest) GetStatusFilter() []v1.Status {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

func (x *GetOrdersRequest) GetSubmittedBy() int64 {
	if x != nil && x.SubmittedBy != nil {
		return *x.SubmittedBy
	}
	return 0
}

func (x *GetOrdersRequest) GetPlacementFrom() string {
	if x != nil && x.PlacementFrom != nil {
		return *x.PlacementFrom
	}
	return ""
}

func (x *GetOrdersRequest) GetPlacementTo() string {
	if x != nil && x.PlacementTo != nil {
		return *x.PlacementTo
	}
	return ""
}

func (x *GetOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetOrdersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*v1.Order            `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrdersResponse) GetOrders() []*v1.Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *GetOrdersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateOrderLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Origin        *v1.Coordinates        `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   *v1.Coordinates        `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderLocationRequest) Reset() {
	*x = UpdateOrderLocationRequest{}
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderLocationRequest) ProtoMessage() {}

func (x *UpdateOrderLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderLocationRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateOrderLocationRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateOrderLocationRequest) GetOrigin() *v1.Coordinates {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *UpdateOrderLocationRequest) GetDestination() *v1.Coordinates {
	if x != nil {
		return x.Destination
	}
	return nil
}

type UpdateOrderLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *v1.Order              `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderLocationResponse) Reset() {
	*x = UpdateOrderLocationResponse{}
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderLocationResponse) ProtoMessage() {}

func (x *UpdateOrderLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderLocationResponse) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOrderLocationResponse) GetOrder() *v1.Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetDronesRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status *DroneStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=admin.v1.DroneStatus,oneof" json:"status,omitempty"` // filter by status if set
	// If true, only drones with assigned_job not null; if false and unassigned_only true, only NULL.
	AssignedOnly   *bool `protobuf:"varint,2,opt,name=assigned_only,json=assignedOnly,proto3,oneof" json:"assigned_only,omitempty"`
	UnassignedOnly *bool `protobuf:"varint,3,opt,name=unassigned_only,json=unassignedOnly,proto3,oneof" json:"unassigned_only,omitempty"`
	// substring match against name or serial_number
	NameOrSerialContains *string `protobuf:"bytes,4,opt,name=name_or_serial_contains,json=nameOrSerialContains,proto3,oneof" json:"name_or_serial_contains,omitempty"`
	PageSize             int32   `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string  `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetDronesRequest) Reset() {
	*x = GetDronesRequest{}
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDronesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDronesRequest) ProtoMessage() {}

func (x *GetDronesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDronesRequest.ProtoReflect.Descriptor instead.
func (*GetDronesRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetDronesRequest) GetStatus() DroneStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DroneStatus_DRONE_STATUS_UNSPECIFIED
}

func (x *GetDronesRequest) GetAssignedOnly() bool {
	if x != nil && x.AssignedOnly != nil {
		return *x.AssignedOnly
	}
	return false
}

func (x *GetDronesRequest) GetUnassignedOnly() bool {
	if x != nil && x.UnassignedOnly != nil {
		return *x.UnassignedOnly
	}
	return false
}

func (x *GetDronesRequest) GetNameOrSerialContains() string {
	if x != nil && x.NameOrSerialContains != nil {
		return *x.NameOrSerialContains
	}
	return ""
}

func (x *GetDronesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetDronesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetDronesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drones        []*Drone               `protobuf:"bytes,1,rep,name=drones,proto3" json:"drones,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDronesResponse) Reset() {
	*x = GetDronesResponse{}
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDronesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDronesResponse) ProtoMessage() {}

func (x *GetDronesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDronesResponse.ProtoReflect.Descriptor instead.
func (*GetDronesResponse) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetDronesResponse) GetDrones() []*Drone {
	if x != nil {
		return x.Drones
	}
	return nil
}

func (x *GetDronesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateDroneStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DroneId       int64                  `protobuf:"varint,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Status        DroneStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=admin.v1.DroneStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDroneStatusRequest) Reset() {
	*x = UpdateDroneStatusRequest{}
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDroneStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDroneStatusRequest) ProtoMessage() {}

func (x *UpdateDroneStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDroneStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDroneStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDroneStatusRequest) GetDroneId() int64 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

func (x *UpdateDroneStatusRequest) GetStatus() DroneStatus {
	if x != nil {
		return x.Status
	}
	return DroneStatus_DRONE_STATUS_UNSPECIFIED
}

type UpdateDroneStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drone         *Drone                 `protobuf:"bytes,1,opt,name=drone,proto3" json:"drone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDroneStatusResponse) Reset() {
	*x = UpdateDroneStatusResponse{}
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDroneStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDroneStatusResponse) ProtoMessage() {}

func (x *UpdateDroneStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_admin_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDroneStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDroneStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_admin_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDroneStatusResponse) GetDrone() *Drone {
	if x != nil {
		return x.Drone
	}
	return nil
}

var File_api_admin_v1_admin_service_proto protoreflect.FileDescriptor

const file_api_admin_v1_admin_service_proto_rawDesc = "" +
	"\n" +
	" api/admin/v1/admin_service.proto\x12\badmin.v1\x1a\x1eapi/user/v1/user_service.proto\"\xf9\x01\n" +
	"\x05Drone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x05 \x01(\x01R\x03lng\x12\x1b\n" +
	"\tspeed_mph\x18\x06 \x01(\x01R\bspeedMph\x12&\n" +
	"\fassigned_job\x18\a \x01(\x03H\x00R\vassignedJob\x88\x01\x01\x12-\n" +
	"\x06status\x18\b \x01(\x0e2\x15.admin.v1.DroneStatusR\x06statusB\x0f\n" +
	"\r_assigned_job\"\xb5\x02\n" +
	"\x10GetOrdersRequest\x124\n" +
	"\rstatus_filter\x18\x01 \x03(\x0e2\x0f.user.v1.StatusR\fstatusFilter\x12&\n" +
	"\fsubmitted_by\x18\x02 \x01(\x03H\x00R\vsubmittedBy\x88\x01\x01\x12*\n" +
	"\x0eplacement_from\x18\x03 \x01(\tH\x01R\rplacementFrom\x88\x01\x01\x12&\n" +
	"\fplacement_to\x18\x04 \x01(\tH\x02R\vplacementTo\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageTokenB\x0f\n" +
	"\r_submitted_byB\x11\n" +
	"\x0f_placement_fromB\x0f\n" +
	"\r_placement_to\"c\n" +
	"\x11GetOrdersResponse\x12&\n" +
	"\x06orders\x18\x01 \x03(\v2\x0e.user.v1.OrderR\x06orders\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x9d\x01\n" +
	"\x1aUpdateOrderLocationRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12,\n" +
	"\x06origin\x18\x02 \x01(\v2\x14.user.v1.CoordinatesR\x06origin\x126\n" +
	"\vdestination\x18\x03 \x01(\v2\x14.user.v1.CoordinatesR\vdestination\"C\n" +
	"\x1bUpdateOrderLocationResponse\x12$\n" +
	"\x05order\x18\x01 \x01(\v2\x0e.user.v1.OrderR\x05order\"\xe3\x02\n" +
	"\x10GetDronesRequest\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.admin.v1.DroneStatusH\x00R\x06status\x88\x01\x01\x12(\n" +
	"\rassigned_only\x18\x02 \x01(\bH\x01R\fassignedOnly\x88\x01\x01\x12,\n" +
	"\x0funassigned_only\x18\x03 \x01(\bH\x02R\x0eunassignedOnly\x88\x01\x01\x12:\n" +
	"\x17name_or_serial_contains\x18\x04 \x01(\tH\x03R\x14nameOrSerialContains\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageTokenB\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_assigned_onlyB\x12\n" +
	"\x10_unassigned_onlyB\x1a\n" +
	"\x18_name_or_serial_contains\"d\n" +
	"\x11GetDronesResponse\x12'\n" +
	"\x06drones\x18\x01 \x03(\v2\x0f.admin.v1.DroneR\x06drones\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"d\n" +
	"\x18UpdateDroneStatusRequest\x12\x19\n" +
	"\bdrone_id\x18\x01 \x01(\x03R\adroneId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.admin.v1.DroneStatusR\x06status\"B\n" +
	"\x19UpdateDroneStatusResponse\x12%\n" +
	"\x05drone\x18\x01 \x01(\v2\x0f.admin.v1.DroneR\x05drone*\\\n" +
	"\vDroneStatus\x12\x1c\n" +
	"\x18DRONE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DRONE_STATUS_FIXED\x10\x01\x12\x17\n" +
	"\x13DRONE_STATUS_BROKEN\x10\x022\xdc\x02\n" +
	"\fAdminService\x12D\n" +
	"\tGetOrders\x12\x1a.admin.v1.GetOrdersRequest\x1a\x1b.admin.v1.GetOrdersResponse\x12b\n" +
	"\x13UpdateOrderLocation\x12$.admin.v1.UpdateOrderLocationRequest\x1a%.admin.v1.UpdateOrderLocationResponse\x12D\n" +
	"\tGetDrones\x12\x1a.admin.v1.GetDronesRequest\x1a\x1b.admin.v1.GetDronesResponse\x12\\\n" +
	"\x11UpdateDroneStatus\x12\".admin.v1.UpdateDroneStatusRequest\x1a#.admin.v1.UpdateDroneStatusResponseB.Z,droneDeliveryManagement/api/admin/v1;adminv1b\x06proto3"

var (
	file_api_admin_v1_admin_service_proto_rawDescOnce sync.Once
	file_api_admin_v1_admin_service_proto_rawDescData []byte
)

func file_api_admin_v1_admin_service_proto_rawDescGZIP() []byte {
	file_api_admin_v1_admin_service_proto_rawDescOnce.Do(func() {
		file_api_admin_v1_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_admin_v1_admin_service_proto_rawDesc), len(file_api_admin_v1_admin_service_proto_rawDesc)))
	})
	return file_api_admin_v1_admin_service_proto_rawDescData
}

var file_api_admin_v1_admin_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_admin_v1_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_admin_v1_admin_service_proto_goTypes = []any{
	(DroneStatus)(0),                    // 0: admin.v1.DroneStatus
	(*Drone)(nil),                       // 1: admin.v1.Drone
	(*GetOrdersRequest)(nil),            // 2: admin.v1.GetOrdersRequest
	(*GetOrdersResponse)(nil),           // 3: admin.v1.GetOrdersResponse
	(*UpdateOrderLocationRequest)(nil),  // 4: admin.v1.UpdateOrderLocationRequest
	(*UpdateOrderLocationResponse)(nil), // 5: admin.v1.UpdateOrderLocationResponse
	(*GetDronesRequest)(nil),            // 6: admin.v1.GetDronesRequest
	(*GetDronesResponse)(nil),           // 7: admin.v1.GetDronesResponse
	(*UpdateDroneStatusRequest)(nil),    // 8: admin.v1.UpdateDroneStatusRequest
	(*UpdateDroneStatusResponse)(nil),   // 9: admin.v1.UpdateDroneStatusResponse
	(v1.Status)(0),                      // 10: user.v1.Status
	(*v1.Order)(nil),                    // 11: user.v1.Order
	(*v1.Coordinates)(nil),              // 12: user.v1.Coordinates
}
var file_api_admin_v1_admin_service_proto_depIdxs = []int32{
	0,  // 0: admin.v1.Drone.status:type_name -> admin.v1.DroneStatus
	10, // 1: admin.v1.GetOrdersRequest.status_filter:type_name -> user.v1.Status
	11, // 2: admin.v1.GetOrdersResponse.orders:type_name -> user.v1.Order
	12, // 3: admin.v1.UpdateOrderLocationRequest.origin:type_name -> user.v1.Coordinates
	12, // 4: admin.v1.UpdateOrderLocationRequest.destination:type_name -> user.v1.Coordinates
	11, // 5: admin.v1.UpdateOrderLocationResponse.order:type_name -> user.v1.Order
	0,  // 6: admin.v1.GetDronesRequest.status:type_name -> admin.v1.DroneStatus
	1,  // 7: admin.v1.GetDronesResponse.drones:type_name -> admin.v1.Drone
	0,  // 8: admin.v1.UpdateDroneStatusRequest.status:type_name -> admin.v1.DroneStatus
	1,  // 9: admin.v1.UpdateDroneStatusResponse.drone:type_name -> admin.v1.Drone
	2,  // 10: admin.v1.AdminService.GetOrders:input_type -> admin.v1.GetOrdersRequest
	4,  // 11: admin.v1.AdminService.UpdateOrderLocation:input_type -> admin.v1.UpdateOrderLocationRequest
	6,  // 12: admin.v1.AdminService.GetDrones:input_type -> admin.v1.GetDronesRequest
	8,  // 13: admin.v1.AdminService.UpdateDroneStatus:input_type -> admin.v1.UpdateDroneStatusRequest
	3,  // 14: admin.v1.AdminService.GetOrders:output_type -> admin.v1.GetOrdersResponse
	5,  // 15: admin.v1.AdminService.UpdateOrderLocation:output_type -> admin.v1.UpdateOrderLocationResponse
	7,  // 16: admin.v1.AdminService.GetDrones:output_type -> admin.v1.GetDronesResponse
	9,  // 17: admin.v1.AdminService.UpdateDroneStatus:output_type -> admin.v1.UpdateDroneStatusResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_admin_v1_admin_service_proto_init() }
func file_api_admin_v1_admin_service_proto_init() {
	if File_api_admin_v1_admin_service_proto != nil {
		return
	}
	file_api_admin_v1_admin_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_admin_v1_admin_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_admin_v1_admin_service_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_admin_v1_admin_service_proto_rawDesc), len(file_api_admin_v1_admin_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_admin_v1_admin_service_proto_goTypes,
		DependencyIndexes: file_api_admin_v1_admin_service_proto_depIdxs,
		EnumInfos:         file_api_admin_v1_admin_service_proto_enumTypes,
		MessageInfos:      file_api_admin_v1_admin_service_proto_msgTypes,
	}.Build()
	File_api_admin_v1_admin_service_proto = out.File
	file_api_admin_v1_admin_service_proto_goTypes = nil
	file_api_admin_v1_admin_service_proto_depIdxs = nil
}
