// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/admin/v1/admin_service.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_GetOrders_FullMethodName           = "/admin.v1.AdminService/GetOrders"
	AdminService_UpdateOrderLocation_FullMethodName = "/admin.v1.AdminService/UpdateOrderLocation"
	AdminService_GetDrones_FullMethodName           = "/admin.v1.AdminService/GetDrones"
	AdminService_UpdateDroneStatus_FullMethodName   = "/admin.v1.AdminService/UpdateDroneStatus"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error)
	UpdateOrderLocation(ctx context.Context, in *UpdateOrderLocationRequest, opts ...grpc.CallOption) (*UpdateOrderLocationResponse, error)
	GetDrones(ctx context.Context, in *GetDronesRequest, opts ...grpc.CallOption) (*GetDronesResponse, error)
	UpdateDroneStatus(ctx context.Context, in *UpdateDroneStatusRequest, opts ...grpc.CallOption) (*UpdateDroneStatusResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrdersResponse)
	err := c.cc.Invoke(ctx, AdminService_GetOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateOrderLocation(ctx context.Context, in *UpdateOrderLocationRequest, opts ...grpc.CallOption) (*UpdateOrderLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrderLocationResponse)
	err := c.cc.Invoke(ctx, AdminService_UpdateOrderLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetDrones(ctx context.Context, in *GetDronesRequest, opts ...grpc.CallOption) (*GetDronesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDronesResponse)
	err := c.cc.Invoke(ctx, AdminService_GetDrones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateDroneStatus(ctx context.Context, in *UpdateDroneStatusRequest, opts ...grpc.CallOption) (*UpdateDroneStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDroneStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_UpdateDroneStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersResponse, error)
	UpdateOrderLocation(context.Context, *UpdateOrderLocationRequest) (*UpdateOrderLocationResponse, error)
	GetDrones(context.Context, *GetDronesRequest) (*GetDronesResponse, error)
	UpdateDroneStatus(context.Context, *UpdateDroneStatusRequest) (*UpdateDroneStatusResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrders not implemented")
}
func (UnimplementedAdminServiceServer) UpdateOrderLocation(context.Context, *UpdateOrderLocationRequest) (*UpdateOrderLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrderLocation not implemented")
}
func (UnimplementedAdminServiceServer) GetDrones(context.Context, *GetDronesRequest) (*GetDronesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDrones not implemented")
}
func (UnimplementedAdminServiceServer) UpdateDroneStatus(context.Context, *UpdateDroneStatusRequest) (*UpdateDroneStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDroneStatus not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetOrders(ctx, req.(*GetOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateOrderLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateOrderLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateOrderLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateOrderLocation(ctx, req.(*UpdateOrderLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetDrones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDronesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetDrones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetDrones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetDrones(ctx, req.(*GetDronesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateDroneStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDroneStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateDroneStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpdateDroneStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateDroneStatus(ctx, req.(*UpdateDroneStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrders",
			Handler:    _AdminService_GetOrders_Handler,
		},
		{
			MethodName: "UpdateOrderLocation",
			Handler:    _AdminService_UpdateOrderLocation_Handler,
		},
		{
			MethodName: "GetDrones",
			Handler:    _AdminService_GetDrones_Handler,
		},
		{
			MethodName: "UpdateDroneStatus",
			Handler:    _AdminService_UpdateDroneStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/admin/v1/admin_service.proto",
}
